# Generated by Django 4.0 on 2021-12-20 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.FileField(upload_to='files/')),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aviasalesApp.airplane')),
                ('countryEnd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aviasalesApp.country')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aviasalesApp.person')),
            ],
        ),
    ]
